db:
  image: mysql:5.5
  #build: ./docker/db/
  environment:
    MYSQL_ROOT_PASSWORD: aA123456789
#   MYSQL_DATABASE: cyberconnector
#   MYSQL_USER: example_db_user
#   MYSQL_PASSWORD: example_db_pass
  ports:
    - "3306:3306"
  volumes:
   - ./docker/db:/docker-entrypoint-initdb.d

web:
  image: tomcat:8.5-jre8
  #build: ./docker/tomcat/
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
#  environment:
#    JDBC_URL: jdbc:mysql://db:3306/cyberconnector?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
#    JDBC_USER: example_db_user
#    JDBC_PASS: example_db_pass
  ports:
   - "8080:8080"
  volumes:
   - ./target/Geoweaver.war:/usr/local/tomcat/webapps/Geoweaver.war
  links:
    - db
